pub const PREFIX_TEXT: &str = r#"//-----------------------------------------------------//
// This file was generated by the solidity_error_to_string
// tool written by @0xSimon on twitter.
//
// The tool can be found at:
//-----------------------------------------------------//

export type SolidityMessageAndArgs = {
    errorMessage: string;
    args: {
      name: string;
      type: string;
      internalType: string;
    }[];
  };
  
  export type FullJasperError = {
    errorName: string;
    solidityMessageAndArgs: SolidityMessageAndArgs;
  };
  
  export type JasperObject = {
    [key: string]: FullJasperError;
  };

"#;
